import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} w-full min-h-full h-screen flex`}>
        <SessionProvider session={session}>
          <main className="flex flex-col w-full h-full bg-yellow-300">
            <Header />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
