import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Image from "next/image";
import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";
import SessionProvider from "@/components/SessionProvider";
import Header from "@/components/Header";
import authOptions from "@/lib/auth";
import { Toaster } from "react-hot-toast";
import TRPCProvider from "@/app/_trpc/Provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`relative flex  h-fit min-h-screen w-full flex-col`}>
        <SessionProvider session={session}>
          <TRPCProvider>
            <Image
              src="/bg-dark.jpg"
              alt="Picture of the author"
              className="opacity-90"
              fill={true}
              style={{ objectFit: "cover" }}
              placeholder="blur"
              quality={100}
              blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
            />
            <Header />
            <main className="backdrop-blur-xs prose prose-invert z-50 flex h-full w-full max-w-none grow flex-col p-10">
              <Toaster position="top-center" />
              {children}
            </main>
          </TRPCProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
