import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Image from "next/image";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative flex  h-fit min-h-screen w-full flex-col`}
      >
        <SessionProvider session={session}>
          <Image
            src="/bg-dark.jpg"
            alt="Picture of the author"
            className="opacity-90"
            fill={true}
            style={{ objectFit: "cover" }}
            placeholder="blur"
            quality={100}
            blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
          />
          <Header />
          <main className="backdrop-blur-xs prose prose-invert z-50 flex h-full w-full max-w-none grow flex-col p-10">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
